# Generated by Django 3.0.8 on 2020-08-01 16:04

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
